name: Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
    unit:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: "14.x",
        - name: Install dependencies
          run: npm ci
        - name: compile
          run: npm run build
        - name: test
          run:
            export ALCHEMY_API_KEY=${{secrets.ALCHEMY_API_KEY}}
            npm run test


